#!/usr/bin/env bash
# ---------------------------------------------------------------------------
# Build the OS and boot it on qemu-system-riscv64.
#
# This script does four things, in order:
#   1. generate fakeroot.inc, a byte table of host directory names that the
#      toy OS reads as its fake "/" filesystem,
#   2. build os.elf with make,
#   3. locate qemu and an OpenSBI firmware blob,
#   4. exec qemu with our kernel.
#
# Exit the virtual machine with the `halt` command inside the shell, with
# Ctrl-C, or with the qemu escape sequence: Ctrl-A then X.
# ---------------------------------------------------------------------------
set -euo pipefail

# Always operate from the directory containing this script, so paths below are
# relative to the project rather than wherever the user happened to be.
cd "$(dirname "$0")"

# --------------------------------------------------------- fake host tree ---
# Harvest the directory names of the host's root filesystem (directories only,
# everything under /home plus the virtual filesystems is skipped) and turn them
# into a byte table that os.S includes at assembly time.  This gives the toy OS
# a fake but familiar "/" to explore.  Tune with FAKE_LIMIT / FAKE_MAXLEN.
FAKE_LIMIT="${FAKE_LIMIT:-200}"    # at most this many directories
FAKE_MAXLEN="${FAKE_MAXLEN:-100}"  # skip paths longer than this
FAKE_INC="fakeroot.inc"

{
    echo "# generated by run.sh - do not edit"
    # `find /` lists directories; the parenthesised -path clauses prune away
    # /home and the kernel virtual filesystems so we only keep "interesting"
    # top-level paths.  `sort -u` removes duplicates.
    find / -mindepth 1 \
        \( -path /home -o -path /proc -o -path /sys -o -path /dev \
           -o -path /run -o -path /tmp \) -prune -o \
        -type d -print 2>/dev/null \
    | sort -u \
    | awk -v limit="$FAKE_LIMIT" -v maxlen="$FAKE_MAXLEN" '
        # Map every byte value to its ordinal so we can emit ".byte 0xNN,...".
        BEGIN { for (i = 0; i < 256; i++) ord[sprintf("%c", i)] = i }
        length($0) > maxlen { next }        # skip overly long paths
        {
            if (++count > limit) exit       # stop at the limit
            printf ".byte "
            for (i = 1; i <= length($0); i++)
                printf "0x%02x,", ord[substr($0, i, 1)]
            print "0"                           # NUL terminates each entry
        }
        END { print ".byte 0" }                 # empty entry ends the list
    '
} > "$FAKE_INC" || true

# ------------------------------------------------------------------ disk -----
# The OS persists its directory tree on a virtio-blk device backed by a host
# file.  Create the file (zero filled, so the OS sees an empty filesystem and
# builds its default tree) the first time only; afterwards the same file is
# reattached, so directories you made survive across boots.  Delete disk.img
# to start over.  Tune the size with DISK_SIZE.
DISK_IMG="${DISK_IMG:-disk.img}"
DISK_SIZE="${DISK_SIZE:-8M}"
if [ ! -f "$DISK_IMG" ]; then
    truncate -s "$DISK_SIZE" "$DISK_IMG"
fi

# ---------------------------------------------------------------- build -----
# Prefer the "unknown-elf" toolchain but fall back to a Linux-targeted one.
if ! command -v riscv64-unknown-elf-gcc >/dev/null 2>&1 && \
   ! command -v riscv64-linux-gnu-gcc  >/dev/null 2>&1; then
    echo "error: no RISC-V cross compiler found." >&2
    echo "install one with: sudo apt install gcc-riscv64-unknown-elf" >&2
    exit 1
fi
make -s os.elf

# ------------------------------------------------------------ find qemu -----
# Look for qemu on PATH first, then in the bundled .tools directory.  $QEMU can
# be set by the caller to force a specific binary.
QEMU="${QEMU:-}"
if [ -z "$QEMU" ]; then
    if command -v qemu-system-riscv64 >/dev/null 2>&1; then
        QEMU="$(command -v qemu-system-riscv64)"
    elif [ -x ".tools/qemu/qemu-system-riscv64" ]; then
        QEMU=".tools/qemu/qemu-system-riscv64"
    else
        echo "error: qemu-system-riscv64 not found." >&2
        echo "install it with: sudo apt install qemu-system-riscv" >&2
        exit 1
    fi
fi

# --------------------------------------------------------------- bios -------
# qemu needs an OpenSBI firmware blob to run before it jumps into our kernel.
# We probe the usual locations and otherwise trust qemu's built-in default.
BIOS_ARGS=(-bios default)
for f in \
    /usr/share/qemu/opensbi-riscv64-generic-fw_dynamic.bin \
    /usr/lib/qemu/opensbi-riscv64-generic-fw_dynamic.bin \
    .tools/qemu/share/opensbi-riscv64-generic-fw_dynamic.bin
do
    if [ -f "$f" ]; then
        BIOS_ARGS=(-bios "$f")
        break
    fi
done

# --------------------------------------------------------------- boot -------
# -machine virt   : the emulated board (RAM, UART, CLINT, ... at known addrs)
# -nographic      : no display; serial goes to this terminal
# -serial mon:stdio: multiplex the guest UART with the qemu monitor on stdio,
#                    which is what makes Ctrl-A X work
# -kernel os.elf  : load our ELF image and start it (as OpenSBI's payload)
# -drive/-device  : the "SSD": a raw host file exposed as virtio-blk, which the
#                   OS finds on the virtio-mmio bus starting at 0x10001000
echo "booting os.elf on $QEMU (Ctrl-A X to quit)"
exec "$QEMU" \
    -machine virt \
    "${BIOS_ARGS[@]}" \
    -global virtio-mmio.force-legacy=false \
    -drive if=none,format=raw,id=hd0,file="$DISK_IMG" \
    -device virtio-blk-device,drive=hd0 \
    -nographic \
    -serial mon:stdio \
    -kernel os.elf
